server:
  port: 8080

eureka:
  instance:
    hostname: localhost


spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: tasksmicrosevice
          uri: http://localhost:8081/
          predicates:
            - Path=/tasks/**,
        - id: usersmicrosevice
          uri: http://localhost:8082/
          predicates:
            - Path=/users/**
